title = "Davis Nelson InfoSec Blog"
theme = "hello-friend-ng"
baseurl      = ""
languageCode = "en-us"
paginate     = 10
pluralizelisttitles = "false"
[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "Information Security Writeups, News, and Walkthroughs"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true

  # Metadata mostly used in document's head
  description = "home"
  keywords = "homepage, blog"
  images = [""]

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "Davis Nelson - InfoSec Blog"
    subtitle = "Cloud and Network Security Writeups, News, and Walkthroughs"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "cd ~/"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "code"
    name       = "Code"
    url        = "/code"
  [[menu.main]]
    identifier = "Red Team"
    name       = "Red Team"
    url        = "/Red Team"
  [[menu.main]]
    identifier = "infrastructure"
    name       = "Infrastructure"
    url        = "/infrastructure"
